swagger: "2.0"
info:
  version: "1.0.0"
  title: Transaction Management API
paths:
  /transactions:
    get:
      summary: Get all transactions for the current month
      security:
        - BearerAuth: []
      description: Returns a list of all transactions made by the user for the current month.
      responses:
        200:
          description: Success - Retrieved list of transactions
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
          examples:
            application/json: 
              - id: "trans123"
                date: "2024-03-01T09:00:00Z"
                amount: 150.00
                description: "Grocery Shopping"
                balance: 950.00
                transactionType: "Debit"
                category: "Food"
                note: "Weekly groceries"
        401:
          description: Unauthorized - Invalid token
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json: 
              error: "Unauthorized access - token invalid"
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json: 
              error: "Access forbidden - insufficient privileges"
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json: 
              error: "Internal server error - please try again later"
    post:
      summary: Add a new transaction
      security:
        - BearerAuth: []
      description: Adds a new transaction to the user's transaction list.
      parameters:
        - in: body
          name: transaction
          description: Object representing the new transaction
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        200:
          description: Success - Transaction successfully added
          schema:
            $ref: '#/definitions/Transaction'
          examples:
            application/json:
              id: "trans124"
              date: "2024-03-02T11:00:00Z"
              amount: 75.00
              description: "Online Subscription"
              balance: 875.00
              transactionType: "Debit"
              category: "Entertainment"
              note: "Monthly subscription"
        400:
          description: Bad Request - Data validation error
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json: 
              error: "Bad Request - Missing required fields"
        401:
          description: Unauthorized - Invalid token
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json: 
              error: "Unauthorized access - token invalid"
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json: 
              error: "Access forbidden - insufficient privileges"
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json: 
              error: "Internal server error - please try again later"
  /transactions/{transactionId}:
    get:
      summary: Get details of a transaction
      security:
        - BearerAuth: []
      description: Returns the details of a specific transaction identified by {transactionId}.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction to retrieve details
      responses:
        200:
          description: Success - Retrieved transaction details
          schema:
            $ref: "#/definitions/Transaction"
          examples:
            application/json: 
              id: "trans123"
              date: "2024-03-01T09:00:00Z"
              amount: 150.00
              description: "Grocery Shopping"
              balance: 950.00
              transactionType: "Debit"
              category: "Food"
              note: "Weekly groceries"
        401:
          description: Unauthorized - Invalid token
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json: 
              error: "Unauthorized
              